"""Remove Nullabe from id

Revision ID: 594509afa0e3
Revises: a48d53b0f17f
Create Date: 2022-08-10 12:28:15.982715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594509afa0e3'
down_revision = 'a48d53b0f17f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
