"""test

Revision ID: 997df5ef41fd
Revises: 594509afa0e3
Create Date: 2022-08-10 12:30:50.814840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997df5ef41fd'
down_revision = '594509afa0e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
